server:
  port: 9001

spring:
  application:
    name: emp
  profiles:
    active: ut
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      #数据库连接在具体的环境对应的profile中配置
#      url: jdbc:mysql://172.10.10.69:3306/emp?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: ikentop
#      password: 18002503040
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        minimum-idle: 3
        maximum-pool-size: 24
        pool-name: ${spring.application.name}-CP
        idle-timeout: 10000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        leakDetectionThreshold: 2000
  output:
    ansi:
      enabled: always

mybatis:
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ikentop.biz.provider.model.dto, com.ikentop.biz.provider.model.bo

pagehelper:
  auto-runtime-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    ROOT: info
    com.ikentop: trace

---
spring:
  profiles: mapper-image_record
  datasource:
    username: sa
    password: sa
    schema: classpath:sql/schema/image_record.sql
    data: classpath:sql/data/image_record.sql
    url: jdbc:hsqldb:mem:hsql_db
---
spring:
  profiles: mapper-area
  datasource:
    username: sa
    password: sa
    schema: classpath:sql/schema/area.sql
    data: classpath:sql/data/area.sql
    url: jdbc:hsqldb:mem:hsql_db
---
spring:
  profiles: mapper-function
  datasource:
    username: sa
    password: sa
    schema: classpath:sql/schema/function.sql, classpath:sql/schema/rolePermission.sql, classpath:sql/schema/role.sql, classpath:sql/schema/operatorRole.sql, classpath:sql/schema/operator.sql, classpath:sql/schema/orgType.sql
    data: classpath:sql/data/function.sql
    url: jdbc:hsqldb:mem:hsql_db
---
spring:
  profiles: mapper-operator
  datasource:
    username: sa
    password: sa
    schema: classpath:sql/schema/operator.sql, classpath:sql/schema/operatorRole.sql, classpath:sql/schema/role.sql, classpath:sql/schema/staff.sql, classpath:sql/schema/staffOperator.sql, classpath:sql/schema/organization.sql, classpath:sql/schema/dept.sql, classpath:sql/schema/deptStaff.sql, classpath:sql/schema/image_record.sql
    data: classpath:sql/data/operator.sql
    url: jdbc:hsqldb:mem:hsql_db

